version: "3.8"

services:
  auth_service_database:
    image: postgres
    container_name: auth_service_database
    ports:
      - "5434:5432"
    volumes:
      - ./db_backup:/var/lib/postgresql/data
    restart: on-failure

  auth_service:
    build:
      context: .
    container_name: auth_service
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8001:8000"
    restart: on-failure
    depends_on:
      - auth_service_database
    command: sh -c "/wait-for-it.sh auth_service_database:5432 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
