# Generated by Django 4.0.4 on 2022-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAuthUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_last_name', models.CharField(max_length=64, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('role', models.CharField(default='user', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
